#Worksheet Constants
WORKBOOK_FOR_SST = 'sst.xlsx'
WORKBOOK_MAIN_SHEET= 'Main'
WORKBOOK_TRACKING_SHEET='Tracking'
WORKBOOK_BACKTEST_SHEET='Backtest'
WORKBOOK_INVESTMENT_SHEET='Investment'

#Hardcoded
TOTAL_MONEY_PER_TRADE = 15000


